# Generated by Django 4.2.14 on 2024-07-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_usd', models.IntegerField()),
                ('volume_24h', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='main.coin')),
            ],
            options={
                'unique_together': {('coin', 'date')},
            },
        ),
    ]
